---
name: Generate IP Info

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'
  push:
    branches:
      - main

jobs:
  build:
    name: Gen IP info
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # This will ensure all git history is fetched

    - name: Set up Go 
      uses: actions/setup-go@v3
      with:
        go-version: 1.21

    - name: Install jq
      run: sudo apt install -y jq

    - name: Install gomplate
      run: curl -sSL https://github.com/hairyhenderson/gomplate/releases/download/v3.10.0/gomplate_linux-amd64 -o gomplate && chmod +x gomplate && sudo mv gomplate /usr/local/bin/
  
    - name: Get ip-ranges.json
      run: curl -O https://ip-ranges.amazonaws.com/ip-ranges.json

    - name: Get ip-ranges.json
      run: |
        jq '[.prefixes | group_by(.region) | .[] | {region: .[0].region, prefixes: .}]' ip-ranges.json > grouped_input.json
        gomplate -f template.gomplate -d regions=grouped_input.json > README.md

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Generating IP info
